FROM cyberdojofoundation/python:8dd40e1
LABEL maintainer=jon@jaggersoft.com

RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip3 install --upgrade pytest pytest-cov pytest-mock pytest-random-order

COPY red_amber_green.rb /usr/local/bin
